/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentRecordsRouteImport } from './routes/treatment-records'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DentistsRouteImport } from './routes/dentists'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as MyProfileRouteImport } from './routes/my/profile'
import { Route as MyInvoicesRouteImport } from './routes/my/invoices'
import { Route as MyAppointmentsRouteImport } from './routes/my/appointments'
import { Route as AppTreatmentRecordsRouteImport } from './routes/app/treatment-records'
import { Route as AppSystemRouteImport } from './routes/app/system'
import { Route as AppShiftsRouteImport } from './routes/app/shifts'
import { Route as AppServicesRouteImport } from './routes/app/services'
import { Route as AppPatientsRouteImport } from './routes/app/patients'
import { Route as AppInvoicesRouteImport } from './routes/app/invoices'
import { Route as AppInventoryRouteImport } from './routes/app/inventory'
import { Route as AppDentistsRouteImport } from './routes/app/dentists'
import { Route as AppAppointmentsRouteImport } from './routes/app/appointments'
import { Route as MyInvoicesIndexRouteImport } from './routes/my/invoices.index'
import { Route as MyAppointmentsIndexRouteImport } from './routes/my/appointments.index'
import { Route as MyInvoicesIdRouteImport } from './routes/my/invoices.$id'
import { Route as MyAppointmentsNewRouteImport } from './routes/my/appointments.new'
import { Route as MyAppointmentsIdRouteImport } from './routes/my/appointments.$id'

const TreatmentRecordsRoute = TreatmentRecordsRouteImport.update({
  id: '/treatment-records',
  path: '/treatment-records',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistsRoute = DentistsRouteImport.update({
  id: '/dentists',
  path: '/dentists',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my/profile',
  path: '/my/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyInvoicesRoute = MyInvoicesRouteImport.update({
  id: '/my/invoices',
  path: '/my/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAppointmentsRoute = MyAppointmentsRouteImport.update({
  id: '/my/appointments',
  path: '/my/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTreatmentRecordsRoute = AppTreatmentRecordsRouteImport.update({
  id: '/app/treatment-records',
  path: '/app/treatment-records',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/app/system',
  path: '/app/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/app/shifts',
  path: '/app/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/app/services',
  path: '/app/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/app/patients',
  path: '/app/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/app/invoices',
  path: '/app/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/app/inventory',
  path: '/app/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDentistsRoute = AppDentistsRouteImport.update({
  id: '/app/dentists',
  path: '/app/dentists',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/app/appointments',
  path: '/app/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const MyInvoicesIndexRoute = MyInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyInvoicesRoute,
} as any)
const MyAppointmentsIndexRoute = MyAppointmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyAppointmentsRoute,
} as any)
const MyInvoicesIdRoute = MyInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MyInvoicesRoute,
} as any)
const MyAppointmentsNewRoute = MyAppointmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MyAppointmentsRoute,
} as any)
const MyAppointmentsIdRoute = MyAppointmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MyAppointmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/dentists': typeof DentistsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/shifts': typeof ShiftsRoute
  '/treatment-records': typeof TreatmentRecordsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/dentists': typeof AppDentistsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/services': typeof AppServicesRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/system': typeof AppSystemRoute
  '/app/treatment-records': typeof AppTreatmentRecordsRoute
  '/my/appointments': typeof MyAppointmentsRouteWithChildren
  '/my/invoices': typeof MyInvoicesRouteWithChildren
  '/my/profile': typeof MyProfileRoute
  '/app/': typeof AppIndexRoute
  '/my/appointments/$id': typeof MyAppointmentsIdRoute
  '/my/appointments/new': typeof MyAppointmentsNewRoute
  '/my/invoices/$id': typeof MyInvoicesIdRoute
  '/my/appointments/': typeof MyAppointmentsIndexRoute
  '/my/invoices/': typeof MyInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/dentists': typeof DentistsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/shifts': typeof ShiftsRoute
  '/treatment-records': typeof TreatmentRecordsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/dentists': typeof AppDentistsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/services': typeof AppServicesRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/system': typeof AppSystemRoute
  '/app/treatment-records': typeof AppTreatmentRecordsRoute
  '/my/profile': typeof MyProfileRoute
  '/app': typeof AppIndexRoute
  '/my/appointments/$id': typeof MyAppointmentsIdRoute
  '/my/appointments/new': typeof MyAppointmentsNewRoute
  '/my/invoices/$id': typeof MyInvoicesIdRoute
  '/my/appointments': typeof MyAppointmentsIndexRoute
  '/my/invoices': typeof MyInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/dentists': typeof DentistsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/shifts': typeof ShiftsRoute
  '/treatment-records': typeof TreatmentRecordsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/dentists': typeof AppDentistsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/services': typeof AppServicesRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/system': typeof AppSystemRoute
  '/app/treatment-records': typeof AppTreatmentRecordsRoute
  '/my/appointments': typeof MyAppointmentsRouteWithChildren
  '/my/invoices': typeof MyInvoicesRouteWithChildren
  '/my/profile': typeof MyProfileRoute
  '/app/': typeof AppIndexRoute
  '/my/appointments/$id': typeof MyAppointmentsIdRoute
  '/my/appointments/new': typeof MyAppointmentsNewRoute
  '/my/invoices/$id': typeof MyInvoicesIdRoute
  '/my/appointments/': typeof MyAppointmentsIndexRoute
  '/my/invoices/': typeof MyInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/dentists'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/patients'
    | '/register'
    | '/services'
    | '/shifts'
    | '/treatment-records'
    | '/app/appointments'
    | '/app/dentists'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/patients'
    | '/app/services'
    | '/app/shifts'
    | '/app/system'
    | '/app/treatment-records'
    | '/my/appointments'
    | '/my/invoices'
    | '/my/profile'
    | '/app/'
    | '/my/appointments/$id'
    | '/my/appointments/new'
    | '/my/invoices/$id'
    | '/my/appointments/'
    | '/my/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/dentists'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/patients'
    | '/register'
    | '/services'
    | '/shifts'
    | '/treatment-records'
    | '/app/appointments'
    | '/app/dentists'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/patients'
    | '/app/services'
    | '/app/shifts'
    | '/app/system'
    | '/app/treatment-records'
    | '/my/profile'
    | '/app'
    | '/my/appointments/$id'
    | '/my/appointments/new'
    | '/my/invoices/$id'
    | '/my/appointments'
    | '/my/invoices'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/dentists'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/patients'
    | '/register'
    | '/services'
    | '/shifts'
    | '/treatment-records'
    | '/app/appointments'
    | '/app/dentists'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/patients'
    | '/app/services'
    | '/app/shifts'
    | '/app/system'
    | '/app/treatment-records'
    | '/my/appointments'
    | '/my/invoices'
    | '/my/profile'
    | '/app/'
    | '/my/appointments/$id'
    | '/my/appointments/new'
    | '/my/invoices/$id'
    | '/my/appointments/'
    | '/my/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  DentistsRoute: typeof DentistsRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  PatientsRoute: typeof PatientsRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  ShiftsRoute: typeof ShiftsRoute
  TreatmentRecordsRoute: typeof TreatmentRecordsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppDentistsRoute: typeof AppDentistsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppSystemRoute: typeof AppSystemRoute
  AppTreatmentRecordsRoute: typeof AppTreatmentRecordsRoute
  MyAppointmentsRoute: typeof MyAppointmentsRouteWithChildren
  MyInvoicesRoute: typeof MyInvoicesRouteWithChildren
  MyProfileRoute: typeof MyProfileRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatment-records': {
      id: '/treatment-records'
      path: '/treatment-records'
      fullPath: '/treatment-records'
      preLoaderRoute: typeof TreatmentRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentists': {
      id: '/dentists'
      path: '/dentists'
      fullPath: '/dentists'
      preLoaderRoute: typeof DentistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/profile': {
      id: '/my/profile'
      path: '/my/profile'
      fullPath: '/my/profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/invoices': {
      id: '/my/invoices'
      path: '/my/invoices'
      fullPath: '/my/invoices'
      preLoaderRoute: typeof MyInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/appointments': {
      id: '/my/appointments'
      path: '/my/appointments'
      fullPath: '/my/appointments'
      preLoaderRoute: typeof MyAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/treatment-records': {
      id: '/app/treatment-records'
      path: '/app/treatment-records'
      fullPath: '/app/treatment-records'
      preLoaderRoute: typeof AppTreatmentRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/system': {
      id: '/app/system'
      path: '/app/system'
      fullPath: '/app/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/shifts': {
      id: '/app/shifts'
      path: '/app/shifts'
      fullPath: '/app/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/services': {
      id: '/app/services'
      path: '/app/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/patients': {
      id: '/app/patients'
      path: '/app/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/app/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/app/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dentists': {
      id: '/app/dentists'
      path: '/app/dentists'
      fullPath: '/app/dentists'
      preLoaderRoute: typeof AppDentistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/app/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/invoices/': {
      id: '/my/invoices/'
      path: '/'
      fullPath: '/my/invoices/'
      preLoaderRoute: typeof MyInvoicesIndexRouteImport
      parentRoute: typeof MyInvoicesRoute
    }
    '/my/appointments/': {
      id: '/my/appointments/'
      path: '/'
      fullPath: '/my/appointments/'
      preLoaderRoute: typeof MyAppointmentsIndexRouteImport
      parentRoute: typeof MyAppointmentsRoute
    }
    '/my/invoices/$id': {
      id: '/my/invoices/$id'
      path: '/$id'
      fullPath: '/my/invoices/$id'
      preLoaderRoute: typeof MyInvoicesIdRouteImport
      parentRoute: typeof MyInvoicesRoute
    }
    '/my/appointments/new': {
      id: '/my/appointments/new'
      path: '/new'
      fullPath: '/my/appointments/new'
      preLoaderRoute: typeof MyAppointmentsNewRouteImport
      parentRoute: typeof MyAppointmentsRoute
    }
    '/my/appointments/$id': {
      id: '/my/appointments/$id'
      path: '/$id'
      fullPath: '/my/appointments/$id'
      preLoaderRoute: typeof MyAppointmentsIdRouteImport
      parentRoute: typeof MyAppointmentsRoute
    }
  }
}

interface MyAppointmentsRouteChildren {
  MyAppointmentsIdRoute: typeof MyAppointmentsIdRoute
  MyAppointmentsNewRoute: typeof MyAppointmentsNewRoute
  MyAppointmentsIndexRoute: typeof MyAppointmentsIndexRoute
}

const MyAppointmentsRouteChildren: MyAppointmentsRouteChildren = {
  MyAppointmentsIdRoute: MyAppointmentsIdRoute,
  MyAppointmentsNewRoute: MyAppointmentsNewRoute,
  MyAppointmentsIndexRoute: MyAppointmentsIndexRoute,
}

const MyAppointmentsRouteWithChildren = MyAppointmentsRoute._addFileChildren(
  MyAppointmentsRouteChildren,
)

interface MyInvoicesRouteChildren {
  MyInvoicesIdRoute: typeof MyInvoicesIdRoute
  MyInvoicesIndexRoute: typeof MyInvoicesIndexRoute
}

const MyInvoicesRouteChildren: MyInvoicesRouteChildren = {
  MyInvoicesIdRoute: MyInvoicesIdRoute,
  MyInvoicesIndexRoute: MyInvoicesIndexRoute,
}

const MyInvoicesRouteWithChildren = MyInvoicesRoute._addFileChildren(
  MyInvoicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  DentistsRoute: DentistsRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  PatientsRoute: PatientsRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  ShiftsRoute: ShiftsRoute,
  TreatmentRecordsRoute: TreatmentRecordsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppDentistsRoute: AppDentistsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppServicesRoute: AppServicesRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppSystemRoute: AppSystemRoute,
  AppTreatmentRecordsRoute: AppTreatmentRecordsRoute,
  MyAppointmentsRoute: MyAppointmentsRouteWithChildren,
  MyInvoicesRoute: MyInvoicesRouteWithChildren,
  MyProfileRoute: MyProfileRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
