/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentRecordsRouteImport } from './routes/treatment-records'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DentistsRouteImport } from './routes/dentists'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'

const TreatmentRecordsRoute = TreatmentRecordsRouteImport.update({
  id: '/treatment-records',
  path: '/treatment-records',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistsRoute = DentistsRouteImport.update({
  id: '/dentists',
  path: '/dentists',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/dentists': typeof DentistsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/services': typeof ServicesRoute
  '/shifts': typeof ShiftsRoute
  '/treatment-records': typeof TreatmentRecordsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/dentists': typeof DentistsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/services': typeof ServicesRoute
  '/shifts': typeof ShiftsRoute
  '/treatment-records': typeof TreatmentRecordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/dentists': typeof DentistsRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/services': typeof ServicesRoute
  '/shifts': typeof ShiftsRoute
  '/treatment-records': typeof TreatmentRecordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/dentists'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/patients'
    | '/services'
    | '/shifts'
    | '/treatment-records'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/dentists'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/patients'
    | '/services'
    | '/shifts'
    | '/treatment-records'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/dentists'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/patients'
    | '/services'
    | '/shifts'
    | '/treatment-records'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  DentistsRoute: typeof DentistsRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  PatientsRoute: typeof PatientsRoute
  ServicesRoute: typeof ServicesRoute
  ShiftsRoute: typeof ShiftsRoute
  TreatmentRecordsRoute: typeof TreatmentRecordsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatment-records': {
      id: '/treatment-records'
      path: '/treatment-records'
      fullPath: '/treatment-records'
      preLoaderRoute: typeof TreatmentRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentists': {
      id: '/dentists'
      path: '/dentists'
      fullPath: '/dentists'
      preLoaderRoute: typeof DentistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  DentistsRoute: DentistsRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  PatientsRoute: PatientsRoute,
  ServicesRoute: ServicesRoute,
  ShiftsRoute: ShiftsRoute,
  TreatmentRecordsRoute: TreatmentRecordsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
